### ISSUE TITLE
Estudo dos testes unitários

### ISSUE THREAD

**Issue by JoelSRangel** [MDS-grupo-9/MDS_Project#54]
## Descrição

O objetivo dessa issue é realizar um estudo dobre testes unitários no projeto de software.

## Tarefas:

- [x] Pesquisar e estudar os conceitos fundamentais de testes unitários.
- [x] Identificar as melhores práticas e padrões para realizar testes unitários efetivos.
- [x] Registrar o resultado do estudo em algum canal de comunicação da equipe

## Critérios de Aceitação:

- Essa issue será considerada como realizada quando, ao final dela, a equipe apresentar um documento (ou um texto explicativo em um canal de comunicação) com a conclusão do estudo.

**Comment by Ninja-Haiyai** [comment]
Feito e documentado no discord
